### ISSUE TITLE
hey pro rold3x please upload a tutorial of it

### ISSUE THREAD

**Issue by darkselle6** [r0ld3x/millierusk_bot#2]
we all are not pro like u sir
upload krdo bro humara bhi bhala ho  jayega
tumhe ccs phek ke marunga charged wale jab jab bhi aayega 

apun bahi he tumahara

**Comment by aafusam** [comment]
It's VPS sided only according to the files present and bash script used

**Comment by r01d3x** [comment]
check roldexverse.t.me i uploaded

**Comment by r0ld3x** [comment]
Its on my channel @roldexverse

OR https://t.me/RoldexVerse/33307
