### ISSUE TITLE
Acknowledgments and recommendations

### ISSUE THREAD

**Issue by IAMDROPPE** [r0ld3x/millierusk_bot#5]
The truth is not necessary, tutorial, everything is very intuitive,
In fact, I would like to know how I can donate to help you with a coffee.

I take advantage beyond that to thank, to say that some gates, and chk do not work.

/vbv = doesn't work.
/chk = does not work.
/au = doesn't work.
/sho = doesn't work.
/wp = doesn't work.
/al = doesn't work.
/cc = doesn't work.
/pf = doesn't work.

**Comment by IAMDROPPE** [comment]
Friend, beyond a donation. Where can I contact personally?
If you could provide an email or a place where we can chat comfortably, it is to agree on a kind of business.

**Comment by r0ld3x** [comment]
> Author

you can talk me in telegram: https://telegram.me/r0ld3x

**Comment by r0ld3x** [comment]
Many peoples are using these source code so the websites are getting high amount of requests, thats why they are dead.
